### ISSUE TITLE
Sync & Fit

### ISSUE THREAD

**Issue by algotrader-au** [louisnw01/lightweight-charts-python#100]
Hi Louis,
Still loving it :-)

A couple of minor isuses:

1. A minor issue in the chart syncing: If an indicator with a lookback period (say ADX(50)) is added on a subchart, then the timescales on the two charts don't align.  The subchart starts with the first available datapoint (i.e. 50 bars in), and aligns with the start of the main chart which starts at bar 0.  A workaround is to put blank/zero data in the first 50 timeslots of the indicator, but that shows as a zero line which is less than accurate.  I guess the subchart displays its own timescale based on the subchart data, but if sync is True, it might be prefereable to use the primary chart data timescale instead?

2. I'm having trouble with .fit() on the first rendering of the chart.  Once I set new data from another instrument, the chart automatically fits as expected; but the first time the chart renders it squashes the data to the right hand half of the screen.  Same code is populating the chart both times.  Could be coder error on my part, but I can't find what's causing it.

**Comment by louisnw01** [comment]
Hey @algotrader-au,

Glad to hear it!

Chart syncing uses the `subscribeVisibleLogicalRange` method within Lightweight Charts which only pays attention to data index numbers rather than timeframe. This makes sync useful for indicators, but not for different timeframes or other data which doesnt align. (#86 also brought this up in regard to different timeframes).

It's definitely possible, but doesn't appear to be straightforward. I'll go through all the functional aspects (how zooming will behave, performance) and get back to you.

As for your second issue, could you provide a minimal reproducible example, preferably using `ohlcv.csv` data.

Louis

**Comment by louisnw01** [comment]
As for syncing based on timeframe, I have tried to attempt this but Lightweight Charts does not seem to offer a way to do this without glitches and bugs (at least in my implementation).

If you (or anyone else) wants to contribute with an implementation feel free.

**Comment by algotrader-au** [comment]
No problems; would love to help with it, but just have too many 'fronts' open already.  If I get some spare time will come back and look at it.
