### ISSUE TITLE
Using .set() with interval != timedelta(days=1)

### ISSUE THREAD

**Issue by emma-uw** [louisnw01/lightweight-charts-python#15]
Hey. There is a little problem when using .set() and intraday candles. First .set() will modify dataset itself making it unusable later on. 
My workaround was using .copy() when executing _df_datetime_format() method. 

Example:
```
chart = Chart()
#ohlc with time format ("%Y-%m-%d %H:%M%S)
chart.set(candles)

line = chart.create_line()
#not going to work since time column was modified to timestamps on previous .set()
line.set(calculate_sma(candles))
```
![изображение](https://github.com/louisnw01/lightweight-charts-python/assets/135511356/7c5790a6-7fc4-4668-9e4e-babebc20df31)

Getting proper python implementation for these charts is a blessing. Thank you.

**Comment by louisnw01** [comment]
Hi! 

Thanks for pointing this out; the next update will use a copy of the data before applying the datetime formatting. 

If you don't want to modify the codebase, a quick fix for now is to use a column named 'date' rather than 'time', which is actually the reason I didn't notice this sooner!

Thanks again,
Louis

**Comment by louisnw01** [comment]
Fixed!
