### ISSUE TITLE
[BUG] Candlestick limit?

### ISSUE THREAD

**Issue by ironhak** [louisnw01/lightweight-charts-python#376]
### Expected Behavior

I'm plotting a daily chart with data from 2006 to today, it's bugged and it does not display properly:
<img width="848" alt="image" src="https://github.com/louisnw01/lightweight-charts-python/assets/62611612/065467a2-341e-4809-bac7-8ffbed072288">
However, if I select just the last 500 rows of the same dataset with `chart.set(df.tail(500))` it works properly. 
Is there a limit to how many candlesticks are plotted? Is it possible to overcome this limit?
Thank's. 

### Current Behaviour

.

### Reproducible Example

```python
.
```

### Environment

```markdown
- OS:
- Library:
```

**Comment by emma-uw** [comment]
There is no limit. Blank chart is probably due to some imperfections in your old data and .tail(500) work because there isnt any in it. Things to try:
1. Sort your data by datetime. Chart will be blank if some candles are out of order.
2. Drop duplicates in your datetime column. Chart will be blank if 2 candles have the same datetime.

**Comment by ironhak** [comment]
Hello, yes apparently a source I use for some data gives a csv with duplicated rows. 
Sorry for opening this issue.
