### ISSUE TITLE
Intraday data show empty chart with just price axis and the last price

### ISSUE THREAD

**Issue by tariusagi** [louisnw01/lightweight-charts-python#4]
Hi,

I tried creating an intraday chart from a JSON file, but the chart is almost blank with only the grid, the price axis and the last price (like the screenshot). I attached the script and the sample data, could you please check it out?

I guess there's something wrong with the time series, which is updated every few seconds, but I don't know how to make it work with your library.

Anyway, I really like you work. It looks really promising, and I love TradingView.

[intraday_chart.zip](https://github.com/louisnw01/lightweight-charts-python/files/11498188/intraday_chart.zip)
![Image 620](https://github.com/louisnw01/lightweight-charts-python/assets/67716321/62aa470d-3b9a-4d63-a2ac-ffa6dc1b2978)

Best regards,

**Comment by louisnw01** [comment]
Hi, and Thank you!

I took a look at the `intraday.json` you are using and I see a few issues with it:

* It is not chronological
* It contains duplicate times
* It does not occur at regular intervals

Lightweight Charts is quite picky with the data it recieves, so its important to address these before setting the data. For example: 

```python
from lightweight_charts import Chart
import pandas as pd

if __name__ == '__main__':
    raw_df = pd.read_json("intraday.json", lines = True)
    df = pd.DataFrame({
            "time" : pd.to_datetime(raw_df.TradingDate + ' ' + raw_df.Time, format = "%d/%m/%Y %H:%M:%S"),
            "open" : raw_df.Open,
            "high" : raw_df.High,
            "low" : raw_df.Low,
            "close" : raw_df.Close,
            "volume" : raw_df.LastVol
        })

    df = df.drop_duplicates(subset='time')
    df_sorted = df.sort_values('time')
    df_filtered = df_sorted[df_sorted['time'].dt.second % 2 == 0]

    chart = Chart(volume_enabled=False)
    chart.set(df_filtered)
    chart.show(block=True)
```

This removes the duplicate times, sorts them in chronological order, and filters them so that only times with even seconds are used.

**Comment by tariusagi** [comment]
@louisnw01 Thank you very much, I've got it working perfectly now.
