### ISSUE TITLE
Scaling enables dynamic loading of K-lines

### ISSUE THREAD

**Issue by 95ge** [louisnw01/lightweight-charts-python#449]
### Question

Firstly, thank you very much for your open-source code. I have a small need to consult, could you please help me see how to implement it when you have time.
1. If I want to obtain the current number of candlesticks, how can I dynamically load more candlesticks by zooming out with the mouse wheel until the interface appears blank?
2. Is there any related tutorial to see?
3. Thank you again!

**Comment by Genyok** [comment]
Use the range_change event https://lightweight-charts-python.readthedocs.io/en/latest/reference/events.html

**Comment by esteban2006** [comment]
@95ge  in relation to your question
1 you could simple the get the lenght of you df, 

```
import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# Get the number of rows
length = len(df)
print(length)  # Output will be 3

```

1.1. how can I dynamically load more candlesticks by zooming out with the mouse wheel until the interface appears blank, i belive this this part of the lib so far, but if what you are looking for is to increase the amount of candles as you scroll your mouse wheel, you need to add an event listener to on the bundle.js file, to track the mouse wheel so that you can add more candles at the beggining of the chart ... also keep in mind the limitation of the lib about the max number of candles that can be handle.

2. 

- here you are for the mouse wheel [event listener](https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event)
- [pandas len](https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event)
