### ISSUE TITLE
Here is a very weird thing I am encountering. Need Help.

### ISSUE THREAD

**Issue by anilwarbhe** [louisnw01/lightweight-charts-python#455]
### Question

The following code works for "ohlcv-ok.csv" but does not for "ohlcv-nok.csv"
[ohlcv-nok.csv](https://github.com/user-attachments/files/17089727/ohlcv-nok.csv)
[ohlcv-ok.csv](https://github.com/user-attachments/files/17089728/ohlcv-ok.csv)

Why this strange phenomena?
I need your help.

### Code example

```python
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart()

    # Columns: time | open | high | low | close | volume
    df = pd.read_csv('ohlcv-nok.csv') #"""BUT THIS DOES NOT RENDER THE CANDLESTICK CHART"""
    # df = pd.read_csv('ohlcv-ok.csv') #"""THIS RENDERS THE CANDLESTICK CHART"""
    chart.set(df)
    chart.show(block=True)
```

**Comment by esteban2006** [comment]
hello @anilwarbhe  for some reason your data frame structure is returning null at data check ups, 

https://github.com/user-attachments/assets/b34cf4a0-8efe-4144-89cf-529760860870


are you getting live data?
or are you loading it from csv?

the are problems when loading from csv as bites maysligh change, this was happening to me a lot when loading from csv but stopped when loading data directly from a provider into pandas df

**Comment by esteban2006** [comment]
@anilwarbhe I undestand your point but the same happened to me, I was having problems after loading 20,000 candle bars, so i guess you are in the same positions now, for some reason data coming from csv files are always come corrupted to lightweight lib, so since my project is very small i did not put too much effort on it, but my suggestion is for you to keep data lower than 20,000 candle bars and if you find a solution to loading from csv and keep the software running with no issues please share your approach

**Comment by armeya25** [comment]
why dont you break up 2000 candles in equal parts and then update them

**Comment by louisnw01** [comment]
Hey @anilwarbhe,

A couple stray duplicate data points:

```
 Unnamed: 0           545
date          2015-12-31
open              120.88
high              122.42
low               120.04
close             121.88
volume           5139521
Name: 545, dtype: object

 Unnamed: 0           544
date          2015-12-31
open              120.88
high              122.42
low               120.04
close             121.88
volume           5139521
Name: 544, dtype: object
```
