### ISSUE TITLE
Inverse Sync

### ISSUE THREAD

**Issue by krazatchu** [louisnw01/lightweight-charts-python#86]
Sync appears to work in the the direction of the child only.
I've added to the bottom of the subchart class: 

` # inverse sync
        self.run_script(f'''
            {self.id}.chart.timeScale().subscribeVisibleLogicalRangeChange((timeRange) => {{
                {sync_parent_id}.chart.timeScale().setVisibleLogicalRange(timeRange)
            }});
            syncCrosshairs({sync_parent_id}.chart, {self.id}.chart)
        ''')`

I'd like to able to sync series with different time frames (like 1min and 5sec), but that seems out of scope for the underlying.

**Comment by louisnw01** [comment]
Hey @krazatchu,

I wanted this behavior when I was first implementing `sync`, however after testing with each chart synced to one another, scrolling behavior became quite buggy as each chart moves the other in a loop. This could potentially be solved by only subscribing to the chart which is currently being hovered over.

As for timeframe sync, the current implementation only moves the charts by their logical range (bar index) and doesn't pay attention to the timeframes of the charts. I think this could be implemented by keeping track of the time in the centre of the logical range, and then setting the logical range of the chart with a different timeframe to be centered around that time. But you would need to keep track of the number of bars in the visible range, so that zooming in/out works as normal.

Feel free to contribute,

Louis

**Comment by louisnw01** [comment]
Sync will now work both ways in the latest version; I'm going to hold off on the timeframe sync for now as it doesn't appear highly requested.

Louis
