### ISSUE TITLE
Enhancement required 

### ISSUE THREAD

**Issue by sbgmicromax** [louisnw01/lightweight-charts-python#9]
Need grid lines visibility in chart option set to true or false and option to plot line charts required please

**Comment by louisnw01** [comment]
Hey, there are no grid lines at the moment but a workaround is to change the grid lines to the same Color as the background. I will implement this feature soon!

As for line charts, it is possible to create a purely line chart by not using `chart.set` and only using the `create_line` method. 

This does have limitations at the moment however; markers and lines cannot be set on the line, however this will be fixed in a future update.

Let me know if this fixes your issue!

Louis

**Comment by louisnw01** [comment]
Hi, 

The `grid` method has now been added to the [Common methods](https://lightweight-charts-python.readthedocs.io/en/latest/docs.html#common-methods) in the latest version.
